### ISSUE TITLE
turtlebot_agent

### ISSUE THREAD

**Issue by elwaaamr** [skousik/simulator#11]
Hello,
Regarding to your simulator repository, I am trying to run the tutorial in [https://github.com/skousik/RTD_tutorial](url), but it gave me the following error:
**************************
Error using turtlebot_agent
The specified superclass 'RTD_agent_2D' contains a parse error, cannot be found on
MATLAB's search path, or is shadowed by another file with the same name.

***************************
Moreover, in simulator repository,[https://github.com/skousik/simulator](url) it said that: **To run this code, you'll need MATLAB. Additional necessary toolboxes will be listed here soon**, so, what are the additional toolboxes that required?

**Comment by skousik** [comment]
Hi Amr, thanks for reaching out. For the first issue, please make sure the [RTD repo](https://github.com/skvaskov/RTD) is on your path (see [here](https://github.com/skousik/RTD_tutorial#installation-requirements) for all requirements). For the second issue, I have updated the README -- no additional toolboxes should be necessary.
